---
abstract: "Tools for integrating with the New Zealand igovt logon service (now \"RealMe\")"
author:
  - 'Grant McLean <grant@catalyst.net.nz>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Authen-NZigovt
requires:
  Crypt::OpenSSL::RSA: 0
  Crypt::OpenSSL::X509: 0
  Date::Parse: 0
  Digest::SHA: 0
  IO::Compress::RawDeflate: 0
  LWP: 0
  URI: 0
  WWW::Curl: 0
  XML::Generator: 0
  XML::LibXML: 0
  perl: 5.010
resources:
  repository: git://github.com/grantm/Authen-NZigovt.git
version: 1.08
